### PR TITLE
Ci: Add Codeql and make trivy work for next containers

### PR DESCRIPTION
**Pull request by tom-rm-meyer-ISST**
## Description
As shown in issue [sig-security#24](https://github.com/eclipse-tractusx/sig-security/issues/24), @scherersebastian showed how to setup the codeql scan and offered the review ([comment](https://github.com/eclipse-tractusx/sig-security/issues/24#issuecomment-1813255706)).
I would love you to do the review!

Also as stated in configuring the trivy scans (#83) I updated the workflows to assign the latest tag to the current main branch to ensure trivy runs on non-release containers, too. Maybe you're also able to review that. If not it's fine. 

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by scherersebastian** [comment]
> Java Backend currently failing due to failure in tests (none given yet). Therefore we need to check to:
> 
>     * either replace autobuild by building with skipTests (will also speed up as soon as tests are given) OR
> 
>     * create tests

@tom-rm-meyer-ISST the easiest way is to build it yourself, as reference you can see the IRS codeql workflow - they also use Java

**Comment by scherersebastian** [comment]
trivy should scan the "latest" images, not "main". I created this as a short term solution, so you can see your findings. At this time no image with a latest tag was released.
I think there is even a TRG for having a "latest" tag.

**Comment by scherersebastian** [comment]
Except of these minor changes, it looks good :)

**Comment by tom-rm-meyer-ISST** [comment]
> trivy should scan the "latest" images, not "main". I created this as a short term solution, so you can see your findings. At this time no image with a latest tag was released. I think there is even a TRG for having a "latest" tag.

I'm confused again:

I adjusted the Workflow to also assign the latest tag to images currently created for main (no release as no specific tag has been set). The [TRG](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-01) seems to only refer to the latest tag for versions in images:
- latest is set, if I create a version 1.5.6 image
- latest is not set, if I just merge to main without further tag

I used the [example worfklow](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05) as basis and now added the latest tag also for the second case.

We could dicsuss in the office hour whats actually the intended behavior.

But for now: Trivy currently scans the main tag? Then in this PR, we could change it to latest.

**Comment by tom-rm-meyer-ISST** [comment]
> > Java Backend currently failing due to failure in tests (none given yet). Therefore we need to check to:
> > ```
> > * either replace autobuild by building with skipTests (will also speed up as soon as tests are given) OR
> > 
> > * create tests
> > ```
> 
> @tom-rm-meyer-ISST the easiest way is to build it yourself, as reference you can see the IRS codeql workflow - they also use Java

Well, we have frontend and backend (javascript and java) that kind of adds some more steps. I'm meanwhile progressing with the testing so that we can merge this PR next week after I merged them :)

**Comment by scherersebastian** [comment]
@tom-rm-meyer-ISST which PR? I can do the changes for you, but please link the PR you are talking of.

**Comment by tom-rm-meyer-ISST** [comment]
> @tom-rm-meyer-ISST which PR? I can do the changes for you, but please link the PR you are talking of.

Sorry @scherersebastian, I was talking about those two PR's (#91, #97) that added some tests. Those have been merged meanwhile. 

After that I found out today, that the setup for the autobuild didn't work
- I needed to bump the java version in the backend
- I needed to setup java accordingly

The latter could be interesting for your recommended setups.

@scherersebastian could you please review this pr now? Everything seems to work now.

**Comment by tom-rm-meyer-ISST** [comment]
@scherersebastian resolved comment. Please approve, if fine :)

**Pull request merged**
