### PR TITLE
Chore: Mandatory change in licensing

### PR DESCRIPTION
**Pull request by eschrewe**
## Description
- inserted the requested changes as demanded in #430 
- does not fully solve the above mentioned issue, since there are still open questions, which are currently unanwered

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by tom-rm-meyer-ISST — DISMISSED** [review]
Thanks! Please also update `NOTICE.md` in folders `frontend` and `backend`.

I meanwhile check if this change also influences the docker notice and the file ending of the documentation files (see [comment](https://matrix.to/#/!qZkRenDKdhqXlBVIfo:matrix.eclipse.org/$KvOMIWW4u8vJylVsF2F_Gl5P3qeyHwFYbTWQSgw4qNs?via=matrix.eclipse.org&via=matrix.org), gonna ask tomorrow in office hour)

**Comment by tom-rm-meyer-ISST** [comment]
@eschrewe the questions pointed out will be adressed next week. For now no need to update
- the docker notice
- the documentation footer

**Comment by eschrewe** [comment]
> Thanks! Please also update `NOTICE.md` in folders `frontend` and `backend`.
> 
> I meanwhile check if this change also influences the docker notice and the file ending of the documentation files (see [comment](https://matrix.to/#/!qZkRenDKdhqXlBVIfo:matrix.eclipse.org/$KvOMIWW4u8vJylVsF2F_Gl5P3qeyHwFYbTWQSgw4qNs?via=matrix.eclipse.org&via=matrix.org), gonna ask tomorrow in office hour)

I updated the NOTICE.md in the backend folder. The frontend folder does not contain a NOTICE.md. 

Since we don't know for sure, whether individual NOTICE.md in /frontend and /backend folder are required at all, Malte decided that we leave the /frontend folder as it currently is and merge that branch in order to meet the deadline tomorrow.

**Review by mhellmeier — APPROVED** [review]
The open points mentioned by @tom-rm-meyer-ISST and @eschrewe have to be considered but shouldn't block this PR.

**Pull request merged**
