### PR TITLE
ci: configure trivy scans

### PR DESCRIPTION
**Pull request by scherersebastian**
## Description

https://github.com/eclipse-tractusx/sig-security/issues/25

Setup trivy scans.
You don't need the trivy config scan - kics does this job.
I configured for you the trivy container scans for your frontend and backend.
In future, please add the `latest` tag to your published images and configure the `latest` tag in the trivy workflow config.

### CODE REVIEW

**Review by mhellmeier — COMMENTED** [review]
Looks good so far. The KICS messages could be addressed by changing the version of the images with the commit hash.

**Comment by scherersebastian** [comment]
@mhellmeier  you are correct.
I already resolved the conflicts as "false positives", because the used actions are published by GitHub and Aquasec which are "reputable" sources.
If you want to have the hash instead, please go for it - it's your code :) _(~not meant disrespectfully)_

**Comment by tom-rm-meyer-ISST** [comment]
Added issue #86 to resolve KICS and handling the latest tag for Docker Hub.

**Review by tom-rm-meyer-ISST — APPROVED** [review]
LGTM, solves https://github.com/eclipse-tractusx/sig-security/issues/25

**Pull request merged**
