### PR TITLE
Create zap.yml

### PR DESCRIPTION
**Pull request by RoKrish14**
## Description
OWASP ZAP tool has been configured to perform DAST scans.

## Prerequisite
Please specify the URL to be scanned under:

`target: 'www.targeturl.com'`

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [ ] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [ ] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Comment by RoKrish14** [comment]
@tom-rm-meyer-ISST: If you have two separate URL's for each scan, then its good to keep two workflows.
If you have single URL everytime for DAST scan, then just a single workflow will do. 

Ideally, the taget URL has to be manually edited before every scan (if the target URL is different)

**Comment by tom-rm-meyer-ISST** [comment]
Hi @RoKrish14, we're close to INT. Did you manage to test the workflow so that we can continue here before christmas? :)

**Comment by RoKrish14** [comment]
Hi @tom-rm-meyer-ISST, 
Informally Yes, and Formally No. Unified report of ZAP-API and ZAP-full scans is possbile now.
I am preparing for a dry run next week and will invite you for a quick check on ZAP.

Otherwise, I might have to perfrom pentests on API, in addition to what ZAP DAST scans.

**Comment by tom-rm-meyer-ISST** [comment]
> Hi @tom-rm-meyer-ISST, Informally Yes, and Formally No. Unified report of ZAP-API and ZAP-full scans is possbile now. I am preparing for a dry run next week and will invite you for a quick check on ZAP.
> 
> Otherwise, I might have to perfrom pentests on API, in addition to what ZAP DAST scans.

Great! Feel free to schedule a short meeting next week. Availability on my site is great on Tuesday and Wednesday between 10 and 12 am!

**Review by mhellmeier — CHANGES_REQUESTED** [review]
Remember to update the branch with the latest version on `main` to make it mergeable.

**Pull request closed without merging**
